config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :top
  get "/top/top_logout_path"
  get '/top_logout_path', to: 'top#top_logout_path', as: 'top_logout_path'
  #get '/likes', to: 'likes#create' 
  post 'top/new',to:'top#new'
  post '/top/cID',to:'top#cID'
  get '/cID', to: 'top#cID'
  
  post '/likes', to: 'likes#create'
 # get '/like/:id', to: 'likes#destroy', as: 'like'
  get '/likes', to: 'likes#destroy', as: 'like'
  
   post 'top/login', to: 'top#login'
   get '/login', to: 'top#login', as: 'flogin'
  
  get 'top/main',to: 'top#main'
  root 'top#main'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
   has_many :likes
    has_many :likes_users, through: :likes, source: :tweet 
    has_many :likes, dependent: :destroy #ツイートを消すといいねも消え
    has_many :like_users, source: :user, through: :likes
    def like(user)
    likes.create(user_id: user.id)
    end
    
    def unlike(user)
    likes.find_by(user_id: user.id).destroy
    end
    
    def liked?(user) #いいね済みか調べる(true / false)
    like_users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :likes
    has_many :like_tweets, through: :likes, source: :tweet 
    has_many :tweets, dependent: :destroy #ユーザを消すとツイートも消える
    has_many :likes, dependent: :destroy #ユーザを消すといいねも消える
    has_many :like_tweets, source: :tweet, through: :likes
    
    validates :password, presence: true, confirmation: true
    attr_accessor :password, :password_confirmation
    def password=(val)
    if val.present?
    self.pass = BCrypt::Password.create(val)
    end
    @password = val
    end
   
end

app/controllers/LikesController.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        unless tweet.liked?(current_user)
          tweet.like(current_user)
        #user = User.find_by(uid: session[:login_uid])
        #user.like_tweets << tweet
        end
        redirect_to root_path
    end
    def destroy
       # logger << "add "
        #logger.debug params[:tweet_id]
        tweet = Tweet.find_by(params[:id])
        if tweet.liked?(current_user)
            tweet.unlike(current_user)
        end
      #  user = User.find_by(uid: session[:login_uid])
       # tweet.likes.find_by(user_id: user.id).destroy
        redirect_to root_path
    end
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    private
    def current_user
        if session[:login_uid]
            User.find_by(uid: session[:login_uid])
        end
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

    
       def main
           logger.debug( current_user)
           logger.debug( "main")
           #use=User.new(uid: 1,pass: 'one',age: 99)
        if session[:login_uid]!=nil
            @tweets=Tweet.all
            render "main"and return
        else 
            @tweets=Tweet.all
          #  render "main"

        end
    end
    
        

    #___________tweet__________
    def new
         logger.debug("nn")
      @tweet = Tweet.new
    end
    def create
         logger.debug( session[:login_uid])
      @tweet = Tweet.new(message: params[:tweet][:message],user_id: session[:login_uid])
      if @tweet.save
        flash[:notice] = '1レコード追加しました'
        redirect_to '/'
      else
        render 'new'
      end
    end
    def show
    @tweets=Tweet.all
        if params[:tweet].present?
          @tweet = Tweet.find(session[:login_uid])
          logger.debug("show")
           render "main"
        else
            @tweets=Tweet.all
              render "main"
        end
        
    end
    def update
      @tweet = Tweet.find_by(params[:id])
      if @tweet.update(message: params[:tweet][:message])
        flash[:notice] = '1レコード更新しました'
        redirect_to '/'
      else
        render 'main'
      end
    end
    #_____________tweet _________
    
    def flogin
        render "login"
    end
    def login
        @tweets=Tweet.all
        require 'bcrypt'
        if params[:pass]==nil
            
            render "login"
        else
            if User.find_by(uid: params[:uid]) 
                user =User.find_by(uid: params[:uid])
                
                if BCrypt::Password.new(user.pass)== params[:pass]
                    session[:login_uid]= params[:uid]
                      logger.debug("login_go")
                       redirect_to '/'
                else
          
                     render "login"
                end
                
            end
        end
        
    end
    def cID
        if User.find_by(uid: params[:uid]) 
            #エラー
            render "cID"
        else
            #正常
              require 'bcrypt'
            #newpass = BCrypt::Password.create(params[:pass])
           @user = User.new(
                            uid: params[:uid],
                            password: params[:password],
                            password_confirmation: params[:password_confirmation])
            if @user.save
                @tweets=Tweet.all
                redirect_to "/"
            else
                render 'cID'
            end
            
 
        end
    end

    
    def top_logout_path
        session.delete(:login_uid)
        redirect_to top_main_path
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/cID.html.erb
<%= form_tag '/top/cID', method: :post, data: { turbo: false } do %>
    <p>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :password, 'パスワード' %>
    <%= password_field_tag :password %>
    </p>
    <p>
    <%= label_tag  :password_confirmation, 'パスワード(確認)' %>
    <%= password_field_tag :password_confirmation %>
    </p>
     <%= submit_tag '登録' %>
<% end %>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post, data: { turbo: false } do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag '登録' %>
<% end %>

app/views/top/main.html.erb
<%= stylesheet_link_tag "index1", :media => "all" %>

<body>
    <p1>
        <ul>
        <y2>
            <%= link_to ' ホーム ', 'top/main' %>
        </y2>
        <ul></ul>
        <y2>
            <%= link_to ' 話題を検索', 'tweets/new' %>
        </y2>
        <ul></ul>
        <y2>
            <%= link_to ' 通知', 'tweets/new' %>
        </y2>
        <ul></ul>
        <y2>
            <%= link_to ' メッセージ   ', 'tweets/new' %>
        </y2>
        <ul></ul>
        <y2>
            <%= link_to ' ブックマーク', 'tweets/new' %>
        </y2>
    　　<ul></ul><y2><%= link_to ' 新規登録', '/cID' %></y2>
        <ul></ul>
        
        
       <y2>
          <% if current_user %>
                <div id="user-profile" class="visible">
                  <%= link_to 'ログアウト',  '/top_logout_path'  %>
                  
                </div>
          <% else %>
                    <%= link_to 'ログイン', '/login' %>
          <% end %>
        </y2>
        <ul></ul>
        <y2>
            <%= link_to ' もっと見る', 'top/main' %>
        </y2>
        <ul></ul>
        <% if  current_user %>
            <form action="top/new" >
                <button type="submit">ツイートする</button>
            </form>
        <% else %>
        <% end %>
        </ul>
    </p1>
    
    <p2>
        <p2_top>
            <y1>ツイート</y1>
            <y1>ツイートと返信</y1>
            <y1>メディア</y1>
            <y1>いいね！</y1>
        </p2_top>
    
    <p3>    
        <% if flash[:notice] %>
            <%= flash[:notice] %>
        <% end %>
        
        <% @tweets.each do |e| %>
        <ul></ul>
            <k1>
            <p>
            <ul></ul>
                <%= e.message %>
            <ul></ul>
              <% if  current_user %>
                <div id="user-profile" class="visible">
                <%= link_to 'いいね', likes_path(tweet_id: e.id), method: :post %>
                <%= link_to 'いいね削除', like_path(e), method: :get %>
                </div>
              <% else %>
           <% end %>
                <%=link_to '削除', "/tweets/#{e.id}", data: { turbo_method: :delete } %>
                <%=link_to '表示', "/tweets/#{e.id}" %>
                <%=link_to '編集', "/tweets/#{e.id}/edit" %>
            </p>
            </k1>
        <% end %>
    </p3>
    </p2>
</body>

app/views/top/new.html.erb
<% if @tweet.errors.present? %>
    <h3>エラーがあります。</h3>
    <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @tweet , url: {action: :create} do |f| %>
    <%= f.label :message, 'メッセージ' %>
    <%= f.text_field :message %>
    <%= f.submit '登録' %>
<% end %>